# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'ZDProtocolCode' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ZDProtocolCode
  pod 'libextobjc', '~> 0.4.1'

  target 'ZDProtocolCodeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZDProtocolCodeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
